# -*- coding: utf-8 -*-
"""Song Recommendation.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Gpt6rMtPLJ3-BKPpymXf21XVlnsVF9ke

**Spotify Songs Recommendation Project**

1. Install & Import Libraries
"""

# !pip install seaborn scikit-learn --quiet

import pandas as pd
import numpy as np
import google.generativeai as genai
import json
import time

# --- GEMINI API SETUP ---
import os
# REPLACE WITH YOUR ACTUAL KEY IF RUNNING LOCALLY WITHOUT ENV VAR
# BUT ON RENDER/PROD, SET "GEMINI_API_KEY" IN ENVIRONMENT VARIABLES
GEMINI_API_KEY = os.environ.get("GEMINI_API_KEY", "AIzaSyC1typQr_vFhO6Cwo0aKklyAhSig5VspnU")
genai.configure(api_key=GEMINI_API_KEY)

def fetch_song_features_from_gemini(song_name):
    """
    Uses Gemini to estimate audio features for a song not in the dataset.
    Returns a dictionary of features or None if failed.
    """
    model = genai.GenerativeModel('gemini-flash-lite-latest')
    
    prompt = f"""
    Estimate the audio features for the song "{song_name}" as accurately as possible based on Spotify's audio features.
    Return ONLY a valid JSON object with the following keys and values:
    - track_name: (string) correct title
    - track_artist: (string) main artist
    - danceability: (float 0.0-1.0)
    - energy: (float 0.0-1.0)
    - loudness: (float -60.0 to 0.0) typically around -5 to -15
    - speechiness: (float 0.0-1.0)
    - acousticness: (float 0.0-1.0)
    - instrumentalness: (float 0.0-1.0)
    - liveness: (float 0.0-1.0)
    - valence: (float 0.0-1.0)
    - tempo: (float) BPM
    - duration_ms: (int) duration in milliseconds
    
    Do not include any markdown formatting or extra text. Just the JSON.
    """
    
    try:
        response = model.generate_content(prompt)
        # remove potential markdown code blocks
        clean_text = response.text.replace('```json', '').replace('```', '').strip()
        data = json.loads(clean_text)
        return data
    except Exception as e:
        print(f"Error fetching from Gemini: {e}")
        return None


"""Song Recommendation"""

#---------LoadData Set---------
df = pd.read_csv("SongRecommendation.csv")
# Clean up any potential unnamed columns from previous bad writes
df = df.loc[:, ~df.columns.str.contains('^Unnamed')]
# Save the original header for future appending
CSV_HEADER = df.columns.tolist()

#-----PreProcessing-------
# Drop missing track names/artists
df = df.dropna(subset=["track_name", "track_artist"])

# Numerical features (kept for reference or future use)
features = ["danceability", "energy", "loudness", "speechiness", "acousticness",
            "instrumentalness", "liveness", "valence", "tempo", "duration_ms"]

# Remove duplicates based on track_name to keep the dataset clean for searching
df = df.drop_duplicates(subset=["track_name"]).reset_index(drop=True)

#--------- Recommendation System Function ----------


def get_gemini_recommendations(song_name, n_recommendations=5):
    """
    """
    model = genai.GenerativeModel('gemini-flash-lite-latest')
    
    prompt = f"""
    Act as a professional music curator.
    First, analyze the song "{song_name}" deeply. Identify its:
    1. Genre (Specific sub-genre)
    2. Vibe/Mood (e.g., Melancholic, Euphoric, Chill, Aggressive)
    3. Instrumentation/Tone (e.g., Acoustic, Synth-heavy, Bass-boosted)

    Based on this analysis, recommend {n_recommendations} songs that perfectly match this specific audio atmosphere and emotional feel.
    
    Return ONLY a valid JSON array of objects. Each object must have:
    - "track_name": The exact name of the song
    - "track_artist": The main artist name
    
    Example response format:
    [
        {{"track_name": "Song 1", "track_artist": "Artist 1"}},
        {{"track_name": "Song 2", "track_artist": "Artist 2"}}
    ]
    
    Do not include any markdown formatting, explanations, or code blocks. Just the raw JSON string.
    """
    
    try:
        response = model.generate_content(prompt)
        clean_text = response.text.replace('```json', '').replace('```', '').strip()
        recommendations = json.loads(clean_text)
        return recommendations
    except Exception as e:
        print(f"Error getting recommendations from Gemini: {e}")
        return []


def save_new_song(song_name):
    """
    Checks if a song exists in the global DF. If not, fetches from Gemini and saves to CSV.
    """
    global df
    
    # Check if exists (case insensitive)
    if df["track_name"].str.contains(song_name, case=False, na=False).any():
        return # Already exists
        
    print(f"    [Background] Fetching features for new song: '{song_name}'...")
    new_song_data = fetch_song_features_from_gemini(song_name)
    
    if new_song_data:
        # Create a DataFrame for the new row
        new_row = pd.DataFrame([new_song_data])
        
        # Ensure it has all columns
        if "track_id" not in new_row.columns:
                new_row["track_id"] = f"gemini_{int(time.time())}" 
        
        # Reindex to match CSV structure
        row_to_save = new_row.reindex(columns=CSV_HEADER)
        
        # Append to CSV
        try:
            csv_line = row_to_save.to_csv(header=False, index=False)
            with open("SongRecommendation.csv", "a", encoding='utf-8') as f:
                f.write(csv_line)
            
            # Update global DF safely
            df = pd.concat([df, new_row], ignore_index=True)
            print(f"    [Background] Saved '{new_song_data['track_name']}' to dataset.")
        except Exception as e:
            print(f"    [Background] Error saving to CSV: {e}")

def background_data_expansion(searched_song, recommended_songs_list):
    """
    Background worker to expand dataset.
    Args:
        searched_song (str): The song user searched for.
        recommended_songs_list (list): List of dicts with 'track_name' and 'track_artist'.
    """
    print(f"\n[Background] Starting data expansion for search '{searched_song}'...")
    
    # 1. Save the Searched Song
    save_new_song(searched_song)
    
    # 2. Save all Recommended Songs
    for song in recommended_songs_list:
        # We use the names returned by Gemini which are usually accurate
        name = song.get('track_name')
        if name:
            save_new_song(name)
            
    print("[Background] Data expansion complete.\n")


def recommend_songs(song_name, n_recommendations=5):
    """
    Main recommendation entry point.
    Returns the list of recommendations immediately. 
    Does NOT handle data saving (that's done by the caller in background).
    """
    print(f"🤖 Asking Gemini for {n_recommendations} recommendations like '{song_name}'...")
    
    # 1. Get List from Gemini
    gemini_recs = get_gemini_recommendations(song_name, n_recommendations)
    
    if not gemini_recs:
        print("Gemini returned no recommendations.")
        return []

    results = []
    
    # 2. Process each recommendation
    for rec in gemini_recs:
        track_name = rec.get('track_name', 'Unknown')
        track_artist = rec.get('track_artist', 'Unknown')
        
        # Generate Links
        query = f"{track_name} {track_artist}".replace(' ', '+')
        youtube_url = f"https://www.youtube.com/results?search_query={query}"
        spotify_url = f"https://open.spotify.com/search/{query}"
        
        results.append({
            "track_name": track_name,
            "track_artist": track_artist,
            "youtube_url": youtube_url,
            "spotify_url": spotify_url,
            "score": 0.99
        })
        
    return results

if __name__ == "__main__":
    # Test run
    recs = recommend_songs("Tumhe Jo Maine Dekha", n_recommendations=2)
    print(json.dumps(recs, indent=2))
    
    # Simulate background task
    background_data_expansion("Tumhe Jo Maine Dekha", recs)
